# Generated by Django 5.0.6 on 2024-05-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_car_image_car_modifications_modificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('members', models.ManyToManyField(related_name='car_clubs', to='main_app.userprofile')),
            ],
        ),
    ]
